import * as dayjs from "dayjs";

const columnsForClients = [
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`, // format of sort
    sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "名前",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "email",
    required: true,
    label: "E-Mail",
    align: "left",
    field: (row) => row.email,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "celular",
    required: true,
    label: "Celular",
    align: "left",
    field: (row) => row.celular,
    sortable: true,
  },
];

const columnsForTemplate = [
  {
    name: "action",
    align: "left",
    label: "編集・削除機能",
    field: "action",
    format: (val) => `${val}`,
  },
  {
    name: "type",
    label: "種別",
    align: "left",
    field: (row) => row.type || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "template",
    label: "文書名",
    align: "left",
    field: (row) => row.name || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "title",
    label: "タイトル",
    align: "left",
    field: (row) => row.title || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "createHuman",
    label: "制作者",
    align: "left",
    field: (row) => row.created_by || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "create",
    label: "制作日",
    align: "left",
    field: (row) => dayjs(row.created_at.split('T')[0]).format("YYYY年MM月DD日") || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "updateHuman",
    label: "更新者",
    align: "left",
    field: (row) => row.updated_by || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "update",
    label: "更新日",
    align: "left",
    field: (row) => dayjs(row.updated_at.split('T')[0]).format("YYYY年MM月DD日") || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
];

const columnsForTemplateList = [
  {
    name: "type",
    label: "種別",
    align: "left",
    field: (row) => row.type || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "template",
    label: "文書名",
    align: "left",
    field: (row) => row.name || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "title",
    label: "タイトル",
    align: "left",
    field: (row) => row.title || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "createHuman",
    label: "制作者",
    align: "left",
    field: (row) => row.created_by || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "create",
    label: "制作日",
    align: "left",
    field: (row) => dayjs(row.created_at.split('T')[0]).format("YYYY年MM月DD日") || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "updateHuman",
    label: "更新者",
    align: "left",
    field: (row) => row.updated_by || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "update",
    label: "更新日",
    align: "left",
    field: (row) => dayjs(row.updated_at.split('T')[0]).format("YYYY年MM月DD日") || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
];

const columsForPastbook = [
  {
    name: "action",
    align: "left",
    label: "",
    field: "action",
    // sortable: true
  },
  {
    name: "type",
    required: true,
    label: "種別",
    align: "left",
    field: (row) => row.type,
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "施主名",
    align: "left",
    field: (row) => row.family_id,
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "俗名",
    align: "left",
    field: (row) => row.last_name + row.first_name,
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "dharmaname",
    required: true,
    label: "戒名",
    align: "left",
    field: (row) => row.dharma_name || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "birth",
    required: true,
    label: "誕生日",
    align: "left",
    field: (row) => row.birth || '' ? dayjs(row.date_of_birth).format("YYYY年MM月DD日") : '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "death",
    required: true,
    label: "享年",
    align: "left",
    field: (row) => row.death || '' ? dayjs(row.date_of_death).format("YYYY年MM月DD日") : '',
    format: (row) => `${row}`,
    // sortable: true,
  },
  {
    name: "Cemetery",
    required: true,
    label: "墓地番号",
    align: "left",
    field: (row) => row.place_of_death || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
];


const columsnForProfile = [
  
  {
    name: "action",
    align: "left",
    label: "",
    field: "action",
    sortable: true
  },
  {
    name: "id",
    required: true,
    label: "ID",
    align: "left",
    field: (row) => row.id,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "id",
    required: true,
    label: "檀家名",
    align: "left",
    field: (row) => row.danka,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "tel",
    required: true,
    label: "電話番号",
    align: "left",
    field: (row) => row.tel,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "email",
    required: true,
    label: "メールアドレス",
    align: "left",
    field: (row) => row.email,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "postalslug",
    required: true,
    label: "郵便番号",
    align: "left",
    field: (row) => row.postcode,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "address",
    required: true,
    label: "住所",
    align: "left",
    field: (row) => row.address,
    format: (val) => `${val}`,
    sortable: true,
  },
];

const columsForDanka = [
  // {
  //   name: "action",
  //   align: "left",
  //   label: "",
  //   field: "action",
  //   // sortable: true,
  // },
  {
    name: "name",
    required: true,
    label: "名前",
    align: "left",
    field: (row) => (row.last_name || '' ? row.last_name : '') + (row.first_name || '' ? row.first_name : ''),
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "type",
    required: true,
    label: "種別",
    align: "left",
    field: (row) => row.type || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "representative",
    required: true,
    label: "立場",
    align: "left",
    field: (row) => row.representative || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  {
    name: "phone",
    required: true,
    label: "性別",
    align: "left",
    field: (row) => row.gender || '',
    format: (val) => `${val}`,
    // sortable: true,
  },
  // {
  //   name: "postal",
  //   required: true,
  //   label: "郵便番号",
  //   align: "left",
  //   field: (row) => row.postcode || '',
  //   format: (val) => `${val}`,
  //   // sortable: true,
  // },
  // {
  //   name: "address",
  //   required: true,
  //   label: "住所",
  //   align: "left",
  //   field: row => (row.pref || '' ? row.pref : '') + (row.city || '' ? row.city : '') + (row.street || '' ? row.street : '') + (row.address || '' ? row.address : ''),
  //   format: (row) => `${row}`,
  //   // sortable: true,
  // },
  // {
  //   name: "Cemetery",
  //   required: true,
  //   label: "墓地番号",
  //   align: "left",
  //   field: (row) => row.location || '',
  //   format: (val) => `${val}`,
  //   // sortable: true,
  // },
];

const contactAddress = [
  {
    name: "type",
    required: true,
    label: "種別",
    align: "left",
    field: (row) => row.type,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "連絡先",
    align: "left",
    field: (row) => row.last_name + row.first_name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "phone",
    required: true,
    label: "電話番号",
    align: "left",
    field: (row) => row.phone,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "email",
    required: true,
    label: "メールアドレス",
    align: "left",
    field: (row) => row.email,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "action",
    align: "left",
    label: "",
    field: "action",
    sortable: true
  }

];

const emailForms = [
  {
    name: "danka",
    required: true,
    label: "家名",
    align: "left",
    field: (row) => row.last_name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "name",
    required: true,
    label: "名前",
    align: "left",
    field: (row) => row.last_name + row.first_name,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "kana",
    required: true,
    label: "フリガナ",
    align: "left",
    field: (row) => row.last_name_kana + row.first_name_kana,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "email",
    required: true,
    label: "メールアドレス",
    align: "left",
    field: (row) => row.email,
    format: (val) => `${val}`,
    sortable: true,
  }

];

const dankalistDetail = [
  {
    name: "plan",
    required: true,
    label: "法要・年回忌名",
    align: "left",
    field: (row) => row.plan,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "scheduled",
    required: true,
    label: "法要・年回忌年月日",
    align: "left",
    field: (row) => row.scheduled,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "passaway",
    required: true,
    label: "命日から",
    align: "left",
    field: (row) => row.passaway,
    format: (val) => `${val}`,
    sortable: true,
  }
]

export {
  columnsForClients,
  columsForPastbook,
  columsnForProfile,
  columsForDanka,
  columnsForTemplate,
  columnsForTemplateList,
  contactAddress,
  emailForms,
  dankalistDetail,
};
